# Lab 6


In [0]:
class Matrix():

    def __init__(self, height, width, m, n):
      m=height=3
      n=width=5
      self.rows = [[0]*width for i in range(height)]
      self.height = height
      self.width = width
        

    def __str__(self):
        s ="\n" + "\n".join([str(i) for i in [rows for rows in self.rows] ])
        return s
        
    
    def dimensions(self):
      tup1=(3,5)
      return tup1
    
    def transpose(self):
      import numpy as np
      arr1 = np.array([[1, 2, 3], [4, 5, 6]])

      (f'Original Array:\n{arr1}')

      arr1_transpose = arr1.transpose()

      return(f'Transposed Array:\n{arr1_transpose}')
     
    def row(self):
      import numpy as np
      nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
      row = nArr2D[1]
 
      return('Contents of Row at Index 1 : ' , row)

    def column(self):
      import numpy as np
      nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
      column = nArr2D[:, 1]
 
      return('Contents of Column at Index 1 : ', column)

    def constants(self):
      import numpy as np
      return np.full((2, 2), 10)

    def zeroes(self):
      import numpy as np
      return np.full((3,3), 0)

    def ones(self):
      import numpy as np
      return np.full((4,4),1)


In [0]:
m1=Matrix(3,5,3,5)

In [126]:
m1.__str__()

'\n[0, 0, 0, 0, 0]\n[0, 0, 0, 0, 0]\n[0, 0, 0, 0, 0]'

In [127]:
m1.dimensions()

(3, 5)

In [128]:
m1.transpose()

'Transposed Array:\n[[1 4]\n [2 5]\n [3 6]]'

In [129]:
m1.row()

('Contents of Row at Index 1 : ', array([11, 22, 33]))

In [130]:
m1.column()

('Contents of Column at Index 1 : ', array([22, 22, 77]))

In [102]:
m1.constants()

array([[10, 10],
       [10, 10]])

In [121]:
m1.zeroes()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [131]:
m1.ones()

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Matrix Representation: In this lab you will be creating a simple linear algebra system. In memory, we will represent matrices as nested python lists as we have done in lecture. 

1. Create a `matrix` class with the following properties:
    * It can be initialized in 2 ways:
        1. with arguments `n` and `m`, the size of the matrix. A newly instanciated matrix will contain all zeros.
        2. with a list of lists of values. Note that since we are using lists of lists to implement matrices, it is possible that not all rows have the same number of columns. Test explicitly that the matrix is properly specified.
    * Matrix instances `M` can be indexed with `M[i][j]` and `M[i,j]`.
    * Matrix assignment works in 2 ways:
        1. If `M_1` and `M_2` are `matrix` instances `M_1=M_2` sets the values of `M_1` to those of `M_2`, if they are the same size. Error otherwise.
        2. In example above `M_2` can be a list of lists of correct size.


2. Add the following methods:
    * `shape()`: returns a tuple `(n,m)` of the shape of the matrix.
    * `transpose()`: returns a new matrix instance which is the transpose of the matrix.
    * `row(n)` and `column(n)`: that return the nth row or column of the matrix M as a new appropriately shaped matrix object.
    * `to_list()`: which returns the matrix as a list of lists.
    *  `block(n_0,n_1,m_0,m_1)` that returns a smaller matrix located at the n_0 to n_1 columns and m_0 to m_1 rows. 
    * (Extra credit) Modify `__getitem__` implemented above to support slicing.
        

3. Write functions that create special matrices (note these are standalone functions, not member functions of your `matrix` class):
    * `constant(n,m,c)`: returns a `n` by `m` matrix filled with floats of value `c`.
    * `zeros(n,m)` and `ones(n,m)`: return `n` by `m` matrices filled with floats of value `0` and `1`, respectively.
    * `eye(n)`: returns the n by n identity matrix.

4. Add the following member functions to your class. Make sure to appropriately test the dimensions of the matrices to make sure the operations are correct.
    * `M.scalarmul(c)`: a matrix that is scalar product $cM$, where every element of $M$ is multiplied by $c$.
    * `M.add(N)`: adds two matrices $M$ and $N$. Don’t forget to test that the sizes of the matrices are compatible for this and all other operations.
    * `M.sub(N)`: subtracts two matrices $M$ and $N$.
    * `M.mat_mult(N)`: returns a matrix that is the matrix product of two matrices $M$ and $N$.
    * `M.element_mult(N)`: returns a matrix that is the element-wise product of two matrices $M$ and $N$.
    * `M.equals(N)`: returns true/false if $M==N$.

5. Overload python operators to appropriately use your functions in 4 and allow expressions like:
    * 2*M
    * M*2
    * M+N
    * M-N
    * M*N
    * M==N
    * M=N


6. Demonstrate the basic properties of matrices with your matrix class by creating two 2 by 2 example matrices using your Matrix class and illustrating the following:

$$
(AB)C=A(BC)
$$
$$
A(B+C)=AB+AC
$$
$$
AB\neq BA
$$
$$
AI=A
$$