# LAB 6

problem 1: 

In [154]:
#solution
class Matrix:
    def matrix(self,n,m):
        empty=0
        board=[[empty]*n for i in range(m)]
        board=np.array(board)
        return board
mat=Matrix()

In [160]:
#test run
practice=mat.matrix(2,5)
print("n x m matrix:")
print(practice) #prints the n x m matrix
print("specific list within the list:")
print(practice[2]) #prints a specific list within the list 
print("initializes another list & sets them equal in value:")
practice1=practice #initializes another list, sets them equal in value
print(practice1) #prints the second list out 

n x m matrix:
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
specific list within the list:
[0 0]
initializes another list & sets them equal in value:
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


problem 2:

In [161]:
#solution
#add the following methods to the matrix class above 
#methods: functions that are defined as part of a class 
#no indication that they need to be "private"
import numpy as np
class Matrix:
    def matrix(self,n,m):
        empty=0
        board=[[empty]*n for i in range(m)]
        board=np.array(board)
        return board
    
    def shape(self,n,m):
        empty=0
        board=[[empty]*n for i in range(m)]
        x = np.array(board)
        x2= np.shape(x)
        return x2
    
    def transpose(self,n,m):
        empty=0
        board=[[empty]*n for i in range(m)]
        x=np.transpose(board)
        return x
    
    def row_col(self,n,m,row,col):
        empty=0
        board=[[empty]*n for i in range(m)]
        print(board[row])
        columns=[]
        for arr in board:
            arr=arr[col]
            columns.append(arr)
        return columns
    
    def to_list(self,n,m): #this method returns the matrix as a list of lists 
        empty=0
        board=[[empty]*n for i in range(m)]
        return board
        
    def block(self, n,m, startRow, startCol, size):
        empty=0
        board=[[empty]*n for i in range(m)]
        x = np.array(board)
        return x[startRow:startRow+size,startCol:startCol+size]
        ###REVIEW THE BLOCK PORTION AGAIN TRY TO MAKE IT FIT THE MATRIX WE CREATE 
    
    
mat=Matrix()

In [173]:
#test run
practice_matrix=mat.matrix(2,5)
practice_shape=mat.shape(2,5)
practice_transpose=mat.transpose(2,5)
#practice_rowcol=mat.row_col(2,5,0,1)
practice_tolist=mat.to_list(2,5)
practice_block=mat.block(2,5,1,3,2)

print("returns the matrix:")
print(practice_matrix)
print("returns the tuple:")
print(practice_shape)
print("returns the transpose matrix:")
print(practice_transpose)
print("returns the row & column:")
practice_rowcol=mat.row_col(2,5,0,1)
print(practice_rowcol) #prints col, not row. figure out how to return row 
print("returns the matrix as a list of lists:")
print(practice_tolist)
print("returns a block of the matrix:")
print(practice_block)

returns the matrix:
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
returns the tuple:
(5, 2)
returns the transpose matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]]
returns the row & column:
[0, 0]
[0, 0, 0, 0, 0]
returns the matrix as a list of lists:
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
returns a block of the matrix:
[]


problem 3:

In [226]:
#solution
import numpy as np
def constant(n,m,c):
    board=[[c]*n for i in range(m)]
    board=np.array(board)
    return board

constant(2,3,5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [216]:
import numpy as np
def zero(n,m):
    zero = np.zeros([n, m], dtype = int) 
    return zero

zero(2,3)

array([[0, 0, 0],
       [0, 0, 0]])

In [217]:
import numpy as np
def one(n,m):
    one = np.ones([n, m], dtype = int) 
    return one

one(2,3)

array([[1, 1, 1],
       [1, 1, 1]])

In [225]:
def identity(n):
    board=[[n]*n for i in range(n)]
    board=np.array(board)
    return board

identity(3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

problem 4: 

M.scalarmul(c): a matrix that is scalar product $cM$, where every element of $M$ is multiplied by $c$.

M.add(N): adds two matrices $M$ and $N$. Don’t forget to test that the sizes of the matrices are compatible for this and all other operations.

M.sub(N): subtracts two matrices $M$ and $N$.

M.mat_mult(N): returns a matrix that is the matrix product of two matrices $M$ and $N$.

M.element_mult(N): returns a matrix that is the element-wise product of two matrices $M$ and $N$.

M.equals(N): returns true/false if $M==N$.

In [241]:
#solution
import numpy as np
class Matrix:
    def __init__(self,n,m,N,M,value_one,value_two,c):
        empty=0
        board=[[empty]*n for i in range(m)]
        board=np.array(board)
        board[board==empty]=c
        self._scalarmul=board
        
        board1=[[value_one]*n for i in range(m)]
        board1=np.array(board1)
        board2=[[value_two]*n for i in range(m)]
        board2=np.array(board2)
        out_add = np.add(board1, board2)
        self._add=out_add
        out_sub = np.subtract(board1, board2) 
        self._sub=out_sub
        out_mult= np.multiply(board1, board2)
        self._mult=out_mult
        
        #out_matmul=np.matmul(board1,board2).shape
        #self._matmul=out_matmul
        out_bool=np.array_equal(board1,board2)
        self._bool=out_bool
        
        
mat=Matrix(2,3,2,3,2,3,3)
print("scalar product matrix:")
print(mat._scalarmul)
print("matrix addition:")
print(mat._add)
print("matrix subtraction:")
print(mat._sub)
print("element wise product:")
print(mat._mult)
print("matrix product of two matrices:")
#print(mat._matmul)
print("...")
print("returns true/false:")
print(mat._bool)

scalar product matrix:
[[3 3]
 [3 3]
 [3 3]]
matrix addition:
[[5 5]
 [5 5]
 [5 5]]
matrix subtraction:
[[-1 -1]
 [-1 -1]
 [-1 -1]]
element wise product:
[[6 6]
 [6 6]
 [6 6]]
matrix product of two matrices:
...
returns true/false:
False


problem 5:

In [11]:
#solution
#what is it asking exactly...

In [12]:
#test run

problem 6:

In [240]:
#solution
import numpy as np
class Matrix:
    def __init__(self,n,m,N,M,value_one,value_two,c):
        
        board1=[[value_one]*n for i in range(m)]
        board1=np.array(board1)
        board2=[[value_two]*n for i in range(m)]
        board2=np.array(board2)
        
        a = np.array([[1, 0],[0, 1]]) 
        ex_one= np.matmul(a, board1)
        ex_two=np.matmul(a,board2)
        self._ex_one=ex_one
        self._ex_two=ex_two
        
        
        
        
mat=Matrix(2,2,2,2,2,3,3)

print("problem 6: (AI=A)") #gives you back your original array 
#matmul is weird in that it doesn't rlly work if sizes are different? 
#makes sense i guess
#having that 'a' array hardcoded makes it so that when multiplied together, it gives us back our array
print("example one:")
print(mat._ex_one)
print("example two:")
print(mat._ex_two)
#try actually multiplying like element wise or .dot 

problem 6: (AI=A)
example one:
[[2 2]
 [2 2]]
example two:
[[3 3]
 [3 3]]
