# Lab 6


In [0]:
import numpy as np

Matrix Representation: In this lab you will be creating a simple linear algebra system. In memory, we will represent matrices as nested python lists as we have done in lecture. 

1. Create a `matrix` class with the following properties:
    * It can be initialized in 2 ways:
        1. with arguments `n` and `m`, the size of the matrix. A newly instanciated matrix will contain all zeros.
        2. with a list of lists of values. Note that since we are using lists of lists to implement matrices, it is possible that not all rows have the same number of columns. Test explicitly that the matrix is properly specified.
    * Matrix instances `M` can be indexed with `M[i][j]` and `M[i,j]`.
    * Matrix assignment works in 2 ways:
        1. If `M_1` and `M_2` are `matrix` instances `M_1=M_2` sets the values of `M_1` to those of `M_2`, if they are the same size. Error otherwise.
        2. In example above `M_2` can be a list of lists of correct size.


In [0]:
class matrix:
  def __init__(self,n,m,c=1,N=[[2,2,2],[2,2,2],[2,2,2]]):
    self.n=n
    self.m=m
    self.c=c
    self.N=N
    self.rows = [[1 for self.n in range(n)] for self.m in range(m)]
    print("Matrix: ",self.rows)

  def __getitem__(self, i, j):
    return self.rows[i][j]

  def shape(self):
    s=np.array(self.rows)
    return s.shape

  def transpose(self):
    t=np.array(self.rows)
    return t.transpose()

  def row(self,k):
    return self.rows[k-1]

  def column(self,l):
    lst=[]
    for i in range(self.n):
      lst.append(self.rows[i][l])
    return lst

  def scalarmul(self,c): 
    for i in range(self.n+1): 
        for j in range(self.m+1):  
            self.rows[i][j] = self.rows[i][j]*c      
    print("Scalar Product Matrix is : ") 
    for i in range(self.n+1): 
        for j in range(self.m+1): 
            print(self.rows[i][j], end = " ") 
        print() 
  
  def add(self, N):
    if ((len(self.rows)  != len(N)) or (len(self.rows[0]) != len(N[0]))):
      print('Dimentions don\'t agree')
    for i in range(self.n+1):
      for j in range(self.m+1):
        self.rows[i][j] = self.rows[i][j] + N[i][j]
    print("Addition of Matrices is : ") 
    for i in range(self.n+1): 
        for j in range(self.m+1): 
            print(self.rows[i][j], end = " ") 
        print()

  def sub(self, N):
    if ((len(self.rows)  != len(N)) or (len(self.rows[0]) != len(N[0]))):
      print('Dimentions don\'t agree')
    for i in range(self.n+1):
      for j in range(self.m+1):
        self.rows[i][j] = self.rows[i][j] - N[i][j]
    print("Subtration of Matrices is : ") 
    for i in range(self.n+1): 
        for j in range(self.m+1): 
            print(self.rows[i][j], end = " ") 
        print()

  '''def mat_mult(self, N):
    result=[[0 for self.n in range(self.n)] for self.m in range(self.m)]
    for i in range(len(self.rows)):
      for j in range(len(N[0])):
        for k in range(len(N)):
          result[i][j] += self.rows[i][k] * N[k][j]
    for r in result:
      print(r) '''
  def mat_mult(self,N):
    if ((len(self.rows)  != len(N)) or (len(self.rows[0]) != len(N[0]))):
      print('Dimentions don\'t agree')
    a=np.array(self.rows)
    b=np.array(N)
    c=np.dot(a,b)
    print("Product of matrices: ")
    return c

  def element_mult(self, N):
    if ((len(self.rows)  != len(N)) or (len(self.rows[0]) != len(N[0]))):
      print('Dimentions don\'t agree')
    for i in range(self.n+1):
      for j in range(self.m+1):
        self.rows[i][j] = self.rows[i][j] * N[i][j]
    print("Elementwise product of Matrices is : ") 
    for i in range(self.n+1): 
        for j in range(self.m+1): 
            print(self.rows[i][j], end = " ") 
        print()
  
  def equals(self, N):
    token=0
    if ((len(self.rows)  != len(N)) or (len(self.rows[0]) != len(N[0]))):
      print('Matrices not equal')
    for i in range(self.n+1):
      for j in range(self.m+1):
        if self.rows[i][j]!=N[i][j]:
          token=1
    if (token==1):
      print("Matrices not equal")
    else:
      print("Matrices are equal")

  def __mul__(self, other): 
    return self.rows*other.c
  
  def __add__(self, other):
    if ((len(self.rows)  != len(other.N)) or (len(self.rows[0]) != len(other.N[0]))):
      print('Dimentions don\'t agree')
    for i in range(self.n+1):
      for j in range(self.m+1):
        self.rows[i][j] = self.rows[i][j] + other.N[i][j]
    print("Addition of Matrices is : ") 
    for i in range(self.n+1): 
        for j in range(self.m+1): 
            print(self.rows[i][j], end = " ") 
        print()

  def __sub__(self,other):
    return self.rows - other.N


In [52]:
M_1=matrix(3,3)
M_2=[[2,2,2],[2,2,2],[2,2,2]]
print("Matrix M_2: ",M_2)
M_2=M_1
print("Matrix M_2 after assigning M_1: ",M_2.rows)
print("For given i,j, M[i][j]: ",M_1.rows[2][2])
M=matrix(3,3,2)
print(M*2)

Matrix:  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
Matrix M_2:  [[2, 2, 2], [2, 2, 2], [2, 2, 2]]
Matrix M_2 after assigning M_1:  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
For given i,j, M[i][j]:  1
Matrix:  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]


AttributeError: ignored

2. Add the following methods:
    * `shape()`: returns a tuple `(n,m)` of the shape of the matrix.
    * `transpose()`: returns a new matrix instance which is the transpose of the matrix.
    * `row(n)` and `column(n)`: that return the nth row or column of the matrix M as a new appropriately shaped matrix object.
    * `to_list()`: which returns the matrix as a list of lists.
    *  `block(n_0,n_1,m_0,m_1)` that returns a smaller matrix located at the n_0 to n_1 columns and m_0 to m_1 rows. 
    * (Extra credit) Modify `__getitem__` implemented above to support slicing.
        

In [453]:
print("Tuple: ", M_1.shape())
print("Transpose: ", M_1.transpose())
print("row(n): ", M_1.row(2))
print("column(n): ", M_1.column(2))

Tuple:  (3, 3)
Transpose:  [[8 8 8]
 [8 8 8]
 [8 8 8]]
row(n):  [8, 8, 8]
column(n):  [8, 8]


3. Write functions that create special matrices (note these are standalone functions, not member functions of your `matrix` class):
    * `constant(n,m,c)`: returns a `n` by `m` matrix filled with floats of value `c`.
    * `zeros(n,m)` and `ones(n,m)`: return `n` by `m` matrices filled with floats of value `0` and `1`, respectively.
    * `eye(n)`: returns the n by n identity matrix.

In [0]:
#contact function
def constant(n,m,c):
    c_mat=[[c for n in range(n)] for m in range(m)]
    const_mat=np.array(c_mat)
    return const_mat.astype(float)

In [444]:
#test
constant(3,4,5)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [0]:
#zeroes & ones function
def zeroes(n,m):
    z_mat=[[0 for n in range(n)] for m in range(m)]
    zero_mat=np.array(z_mat)
    return zero_mat.astype(float)

In [450]:
#test
zeroes(3,4)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
def ones(n,m):
    o_mat=[[1 for n in range(n)] for m in range(m)]
    ones_mat=np.array(o_mat)
    return ones_mat.astype(float)

In [448]:
#test
ones(3,4)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

4. Add the following member functions to your class. Make sure to appropriately test the dimensions of the matrices to make sure the operations are correct.
    * `M.scalarmul(c)`: a matrix that is scalar product $cM$, where every element of $M$ is multiplied by $c$.
    * `M.add(N)`: adds two matrices $M$ and $N$. Don’t forget to test that the sizes of the matrices are compatible for this and all other operations.
    * `M.sub(N)`: subtracts two matrices $M$ and $N$.
    * `M.mat_mult(N)`: returns a matrix that is the matrix product of two matrices $M$ and $N$.
    * `M.element_mult(N)`: returns a matrix that is the element-wise product of two matrices $M$ and $N$.
    * `M.equals(N)`: returns true/false if $M==N$.

In [39]:
M=matrix(3,3)
M.scalarmul(5)
M.add([[2,2,2],[2,2,2],[2,2,2]])
M.sub([[3,3,3],[3,3,3],[3,3,3]])
M.mat_mult([[2,2,2],[2,2,2],[2,2,2]])

Matrix M_1:  [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
Scalar Product Matrix is : 
5 5 5 
5 5 5 
5 5 5 
Addition of Matrices is : 
7 7 7 
7 7 7 
7 7 7 
Subtration of Matrices is : 
4 4 4 
4 4 4 
4 4 4 
Product of matrices: 


array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [40]:
M.element_mult([[5,5,5],[5,5,5],[5,5,5]])
M.equals([[20,20,20],[20,20,20],[20,20,20]])

Elementwise product of Matrices is : 
20 20 20 
20 20 20 
20 20 20 
Matrices are equal


5. Overload python operators to appropriately use your functions in 4 and allow expressions like:
    * 2*M
    * M*2
    * M+N
    * M-N
    * M*N
    * M==N
    * M=N


In [55]:
M=matrix(4,4)
N=matrix(4,4)
M+N

Matrix:  [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]
Matrix:  [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]
Dimentions don't agree


IndexError: ignored

6. Demonstrate the basic properties of matrices with your matrix class by creating two 2 by 2 example matrices using your Matrix class and illustrating the following:

$$
(AB)C=A(BC)
$$
$$
A(B+C)=AB+AC
$$
$$
AB\neq BA
$$
$$
AI=A
$$